apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-group
  labels:
    app: python-group
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-group
  template:
    metadata:
      labels:
        app: python-group
    spec:
      containers:
        - name: python-group
          image: donsolly/python-group:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: python-group
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: python-group
  type: LoadBalancer